# Generated by Django 5.1.6 on 2025-03-06 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Value must be greater or equal to 1",
                            ),
                            django.core.validators.MaxValueValidator(
                                3, message="Value must be less or equal to 3"
                            ),
                        ],
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Task creation date"
                    ),
                ),
                ("finish_at", models.DateTimeField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="tasks/attachments/"
                    ),
                ),
                ("related_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tasks/images/"
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, null=True)),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todo_api.task",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="todo_api.tag"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
