# Generated by Django 5.1.6 on 2025-03-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="finish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
