name: CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Start PostgreSQL and app
        run: docker compose up -d db

      - name: Copy .env for tests
        run: cp .example.env.prod .env.prod

      - name: Run Tox inside Docker
        env:
          DATABASE_URL: postgres://invera:invera@db:5432/invera_todo
        run: docker compose run --rm app tox -e py312-django51,coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install tox
      - run: tox -e lint
